spring:
  cloud:
    stream:
      bindings:
        domainProcessor-in-0:
          destination: web-domain
        domainProcessor-out-0:
          destination: web-domain-active
      kafka:
        bindings:
          domainProcessor-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          domainProcessor-out-0:
            producer:
              configuration:
                value:
                  serializer: org.springframework.kafka.support.serializer.JsonSerializer
        streams:
          binder:
            brokers:  localhost:9092
            configuration:
              commit.interval.ms: 100
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
